from __future__ import annotations

import json
import os
import threading
from pathlib import Path
from typing import Iterator

from .contracts import CARD_KINDS, WorkflowTraceEvent, validate_workflow_trace_event


class TraceConflict(RuntimeError):
    """A trace attempted to violate BYQ sequence ordering."""


class TraceStore:
    """Small BYQ-owned append-only WorkflowTrace store for the Phase 7 seam.

    DSH owns its session persistence separately. This store contains only the
    normalized BYQ envelope and is intentionally independent of DSH logs.
    """

    def __init__(self, root: str | Path) -> None:
        self._root = Path(root).expanduser().resolve()
        self._condition = threading.Condition(threading.RLock())
        self._closed: set[str] = set()
        self._deleted: set[str] = set()

    def append(self, event: WorkflowTraceEvent) -> bool:
        event = validate_workflow_trace_event(event)
        path = self._path(event["session_id"])
        with self._condition:
            if event["session_id"] in self._deleted:
                return False
            existing = self._read(path)
            if existing:
                previous = existing[-1]
                if event["sequence"] < previous["sequence"]:
                    raise TraceConflict("workflow trace sequence moved backwards")
                if event["sequence"] == previous["sequence"]:
                    if event != previous:
                        raise TraceConflict("workflow trace reused a sequence number")
                    return False
                if event["sequence"] != previous["sequence"] + 1:
                    raise TraceConflict("workflow trace sequence contains a gap")
            self._validate_card_revision(event, existing)
            self._root.mkdir(parents=True, exist_ok=True)
            with path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(event, separators=(",", ":"), sort_keys=True) + "\n")
                stream.flush()
                os.fsync(stream.fileno())
            self._condition.notify_all()
            return True

    def next_card_revision(self, session_id: str, card_id: str) -> int:
        with self._condition:
            revisions = [
                event["payload"]["revision"]
                for event in self._read(self._path(session_id))
                if event["kind"] in CARD_KINDS
                and event["payload"].get("card_id") == card_id
                and isinstance(event["payload"].get("revision"), int)
            ]
            return max(revisions, default=0) + 1

    def read(self, session_id: str, *, after_sequence: int = 0) -> list[WorkflowTraceEvent]:
        with self._condition:
            if session_id in self._deleted:
                return []
            return [
                event
                for event in self._read(self._path(session_id))
                if event["sequence"] > after_sequence
            ]

    def close(self, session_id: str) -> None:
        with self._condition:
            self._closed.add(session_id)
            self._condition.notify_all()

    def delete(self, session_id: str) -> None:
        path = self._path(session_id)
        with self._condition:
            self._deleted.add(session_id)
            self._closed.add(session_id)
            path.unlink(missing_ok=True)
            self._condition.notify_all()

    def stream(self, session_id: str, *, after_sequence: int = 0) -> Iterator[WorkflowTraceEvent | None]:
        """Yield replayable events and ``None`` heartbeats until the trace closes."""

        cursor = after_sequence
        while True:
            events = self.read(session_id, after_sequence=cursor)
            for event in events:
                cursor = event["sequence"]
                yield event
            with self._condition:
                if session_id in self._closed:
                    return
                self._condition.wait(timeout=15.0)
            yield None

    def _path(self, session_id: str) -> Path:
        # Session IDs are generated by Gateway and validated by the adapter;
        # retaining a narrow filename rule makes this store safe on its own.
        allowed = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
        if not session_id or any(character not in allowed for character in session_id):
            raise ValueError("invalid session_id for trace storage")
        return self._root / f"{session_id}.ndjson"

    @staticmethod
    def _validate_card_revision(
        event: WorkflowTraceEvent,
        existing: list[WorkflowTraceEvent],
    ) -> None:
        if event["kind"] not in CARD_KINDS:
            return
        card_id = event["payload"]["card_id"]
        revision = event["payload"]["revision"]
        previous = [
            item["payload"]["revision"]
            for item in existing
            if item["kind"] in CARD_KINDS and item["payload"].get("card_id") == card_id
        ]
        if previous and revision <= max(previous):
            raise TraceConflict("workflow card revision did not increase")

    @staticmethod
    def _read(path: Path) -> list[WorkflowTraceEvent]:
        if not path.is_file():
            return []
        events: list[WorkflowTraceEvent] = []
        with path.open(encoding="utf-8") as stream:
            for line in stream:
                if line.strip():
                    events.append(validate_workflow_trace_event(json.loads(line)))
        return events
