"""Thin JSON-RPC stdio client for the pinned official DSH ACP profile.

This module owns only the process transport and the translation from standard
ACP updates to the Adapter's bounded runtime observations. Native ACP session
ids are generated by DSH and must be retained by the Adapter for resume/close.
"""

from __future__ import annotations

import json
import hmac
import os
import queue
import re
import shutil
import signal
import stat
import subprocess
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlsplit

from packages.contracts.domain_call_admission import ACTIONS, parse_observed_arguments

from .types import RuntimeObservation, RuntimeToolResult
from ..research_judgment_acp_provider_overlay import private_provider_overlay
from ..research_judgment_acp_provider_routes import valid_local_provider_token


_ACP_PROTOCOL_VERSION = 1
_MAX_FRAME_BYTES = 16 * 1024 * 1024
_MAX_TOOL_RESULT_BYTES = 1024 * 1024
_MAX_TEXT_BYTES = 8 * 1024 * 1024
_REQUEST_TIMEOUT_SECONDS = 60.0
_MODEL_CONFIG_ID = "model"
_ROOT_BINDING_MARKER = ".byq-acp-root-binding.json"
_ACP_IDENTITY_MODE_ENV = "BYQ_MCP_ACP_IDENTITY_MODE"
_ACP_JUDGMENT_ROOT_MODE = "research-judgment-root-v1"
_ACP_JUDGMENT_OPENCODE_ROUTES = frozenset({
    "opencode-go-responses", "opencode-go-chat", "opencode-go-messages",
    "opencode-zen-responses", "opencode-zen-chat", "opencode-zen-messages",
})
_ACP_JUDGMENT_PROCESS_ENV = frozenset({
    _ACP_IDENTITY_MODE_ENV,
    "BYQ_MCP_ACP_JUDGMENT_TASK_ID",
    "BYQ_MCP_ACP_JUDGMENT_CALL_IDENTITY",
    "BYQ_MCP_ACP_JUDGMENT_SIGNING_KEY",
    "BYQ_MCP_PRODUCT_URL",
})
_ACP_JUDGMENT_ALLOWED_ENV = _ACP_JUDGMENT_PROCESS_ENV | frozenset({
    "BYQ_MCP_URL", "BYQ_RUNTIME_BOOT_ID", "BYQ_OWNER_PRINCIPAL",
    "BYQ_WORKSPACE_ID", "BYQ_ACTOR_PRINCIPAL", "BYQ_TRACE_ID",
    "BYQ_SESSION_ID", "BYQ_DSH_RUN_ID", "BYQ_ROOT_RUN_ID",
})
_ACP_JUDGMENT_FORBIDDEN_ENV = frozenset({
    "BYQ_MCP_ACP_DISCOVERY_TOKEN",
    "BYQ_MCP_ACP_SIGNING_KEY",
    "BYQ_MCP_READ_ONLY_TOKEN",
    "BYQ_MCP_TOKEN",
    "BYQ_MCP_BACKEND_PROOF_TOKEN",
    "BYQ_MCP_ACP_JUDGMENT_PROOF_TOKEN",
    "BYQ_RUNTIME_AUTHORITY_TOKEN",
    "BYQ_RUNTIME_JUDGMENT_TOKEN",
    "BYQ_ACP_JUDGMENT_RUNNER_CONTROL_SECRET",
    "BYQ_GATEWAY_SERVICE_TOKEN",
    "BYQ_CREDENTIAL_RESOLVER_TOKEN",
    "BYQ_PRODUCT_TOKEN",
    "BYQ_NATIVE_ROOT_SESSION_ID",
    "BYQ_CONTINUATION_RESERVATION_ID",
})
_INHERITED_RUNTIME_ENV = frozenset({
    # Minimum host environment needed to launch Node and validate TLS. Do not
    # inherit arbitrary BYQ service configuration, shell preload, or proxy
    # settings into the Product DSH process.
    "PATH", "HOME", "TMPDIR", "LANG", "LC_ALL", "TZ",
    "SSL_CERT_FILE", "SSL_CERT_DIR", "NODE_EXTRA_CA_CERTS",
})
_INTERNAL_SERVICE_SECRETS = frozenset({
    "BYQ_MCP_TOKEN",
    "BYQ_MCP_BACKEND_PROOF_TOKEN",
    "BYQ_MCP_ACP_JUDGMENT_PROOF_TOKEN",
    "BYQ_CREDENTIAL_RESOLVER_TOKEN",
    "BYQ_RUNTIME_AUTHORITY_TOKEN",
    "BYQ_PRODUCT_TOKEN",
    "BYQ_MCP_READ_ONLY_TOKEN",
    "BYQ_MCP_ACP_JUDGMENT_SIGNING_KEY",
    "BYQ_RUNTIME_JUDGMENT_TOKEN",
    "BYQ_FEEDBACK_HUB_ADMIN_TOKEN",
    "BYQ_ACP_JUDGMENT_RUNNER_CONTROL_SECRET",
    "BYQ_GATEWAY_SERVICE_TOKEN",
    "BYQ_FEEDBACK_HUB_RELAY_TOKEN",
    "BYQ_FEEDBACK_HUB_STATUS_SECRET",
    "BYQ_FEEDBACK_PUBLISHER_TOKEN",
    "BYQ_PLUGIN_DEPLOYMENT_TOKEN",
    "BYQ_PHASE10_OBSERVER_TOKEN",
    "BYQ_BOOTSTRAP_ADMIN_PASSWORD",
    "POSTGRES_PASSWORD",
    "TUSHARE_TOKEN",
})
_NATIVE_SESSION_ID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_FINISH_REASONS = {
    "end_turn": "completed",
    "max_tokens": "max_tokens",
    "cancelled": "cancelled",
    "refusal": "failed",
}


class AcpTransportError(RuntimeError):
    """A sanitized transport or protocol failure; wire contents are never included."""


class AcpRpcError(RuntimeError):
    """A JSON-RPC error reduced to its method and numeric code."""

    def __init__(self, method: str, code: int) -> None:
        super().__init__(f"official DSH ACP request failed ({method}, code {code})")
        self.method = method
        self.code = code


@dataclass(frozen=True, slots=True)
class AcpNotification:
    """One ordered ACP notification with an Adapter-local sequence number."""

    method: str
    params: dict[str, Any]
    event_sequence: int | None = None


@dataclass(slots=True)
class _Pending:
    event: threading.Event = field(default_factory=threading.Event)
    response: dict[str, Any] | None = None
    error: BaseException | None = None


@dataclass(slots=True)
class _AcpProcess:
    command: tuple[str, ...]
    cwd: Path
    environment: dict[str, str] = field(repr=False)
    process: subprocess.Popen[bytes] | None = field(default=None, repr=False)
    initialized: bool = False
    _writer_lock: threading.Lock = field(default_factory=threading.Lock, repr=False)
    _pending_lock: threading.Lock = field(default_factory=threading.Lock, repr=False)
    _pending: dict[int, _Pending] = field(default_factory=dict, repr=False)
    _notification_lock: threading.Lock = field(default_factory=threading.Lock, repr=False)
    _notifications: dict[str, queue.Queue[AcpNotification | BaseException]] = field(default_factory=dict, repr=False)
    _sequence: dict[str, int] = field(default_factory=dict, repr=False)
    _next_request_id: int = 1
    _fatal: BaseException | None = field(default=None, repr=False)
    _reader: threading.Thread | None = field(default=None, repr=False)
    _closed: bool = False

    def start(self) -> None:
        if self.process is not None:
            raise AcpTransportError("official DSH ACP process is already started")
        try:
            self.cwd.mkdir(parents=True, exist_ok=True)
            self.process = subprocess.Popen(
                self.command,
                cwd=str(self.cwd),
                env=self.environment,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                # ACP stdout is the protocol stream. Never echo child diagnostics,
                # which can include provider or MCP configuration details.
                stderr=subprocess.DEVNULL,
                close_fds=True,
                start_new_session=(os.name == "posix"),
                bufsize=0,
            )
        except (OSError, ValueError):
            raise AcpTransportError("official DSH ACP process could not be started") from None
        if self.process.stdin is None or self.process.stdout is None:
            self.close()
            raise AcpTransportError("official DSH ACP stdio transport is unavailable")
        self._reader = threading.Thread(
            target=self._read_loop,
            name="byq-dsh-acp-reader",
            daemon=True,
        )
        self._reader.start()
        response = self.request(
            "initialize",
            {
                "protocolVersion": _ACP_PROTOCOL_VERSION,
                "clientCapabilities": {},
                "clientInfo": {"name": "beyondquant-runtime-adapter", "version": "0.10"},
            },
            timeout=_REQUEST_TIMEOUT_SECONDS,
        )
        if (not isinstance(response, dict)
                or response.get("protocolVersion") != _ACP_PROTOCOL_VERSION):
            self.close()
            raise AcpTransportError("official DSH ACP protocol version is incompatible")
        self.initialized = True

    def request(self, method: str, params: dict[str, Any], *, timeout: float | None = None) -> Any:
        pending = self._request_async(method, params)
        if not pending.event.wait(timeout):
            self._discard_pending(pending)
            raise AcpTransportError(f"official DSH ACP request timed out ({method})")
        if pending.error is not None:
            raise pending.error
        response = pending.response
        if not isinstance(response, dict):
            raise AcpTransportError("official DSH ACP returned an invalid response")
        if "error" in response:
            error = response["error"]
            code = error.get("code") if isinstance(error, dict) else None
            if isinstance(code, bool) or not isinstance(code, int):
                raise AcpTransportError("official DSH ACP returned a malformed error")
            raise AcpRpcError(method, code)
        if "result" not in response:
            raise AcpTransportError("official DSH ACP response omitted its result")
        return response["result"]

    def request_async(self, method: str, params: dict[str, Any]) -> _Pending:
        return self._request_async(method, params)

    def _request_async(self, method: str, params: dict[str, Any]) -> _Pending:
        self._raise_if_unavailable()
        pending = _Pending()
        with self._pending_lock:
            request_id = self._next_request_id
            self._next_request_id += 1
            self._pending[request_id] = pending
        try:
            self._write({"jsonrpc": "2.0", "id": request_id, "method": method, "params": params})
        except AcpTransportError as error:
            with self._pending_lock:
                self._pending.pop(request_id, None)
            pending.error = error
            pending.event.set()
        return pending

    def await_response(self, pending: _Pending, *, timeout: float | None = None) -> Any:
        if not pending.event.wait(timeout):
            raise AcpTransportError("official DSH ACP prompt did not settle")
        if pending.error is not None:
            raise pending.error
        response = pending.response
        if not isinstance(response, dict):
            raise AcpTransportError("official DSH ACP returned an invalid response")
        if "error" in response:
            error = response["error"]
            code = error.get("code") if isinstance(error, dict) else None
            if isinstance(code, bool) or not isinstance(code, int):
                raise AcpTransportError("official DSH ACP returned a malformed error")
            raise AcpRpcError("session/prompt", code)
        if "result" not in response:
            raise AcpTransportError("official DSH ACP response omitted its result")
        return response["result"]

    def next_notification(self, session_id: str, timeout: float) -> AcpNotification | None:
        self._raise_if_unavailable(allow_closed_queue=True)
        with self._notification_lock:
            events = self._notifications.setdefault(session_id, queue.Queue())
        try:
            value = events.get(timeout=timeout)
        except queue.Empty:
            return None
        if isinstance(value, BaseException):
            raise value
        return value

    def next_sequence(self, session_id: str) -> int:
        with self._notification_lock:
            value = self._sequence.get(session_id, 0) + 1
            self._sequence[session_id] = value
            return value

    def notify(self, method: str, params: dict[str, Any]) -> None:
        self._write({"jsonrpc": "2.0", "method": method, "params": params})

    def _write(self, message: dict[str, Any]) -> None:
        try:
            encoded = json.dumps(message, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
            raw = encoded.encode("utf-8") + b"\n"
        except (TypeError, ValueError, UnicodeError, RecursionError):
            raise AcpTransportError("official DSH ACP request could not be encoded") from None
        if len(raw) > _MAX_FRAME_BYTES:
            raise AcpTransportError("official DSH ACP request exceeded the protocol bound")
        with self._writer_lock:
            self._raise_if_unavailable()
            process = self.process
            if process is None or process.stdin is None:
                raise AcpTransportError("official DSH ACP stdio transport is unavailable")
            try:
                process.stdin.write(raw)
                process.stdin.flush()
            except (BrokenPipeError, OSError, ValueError):
                self._fail(AcpTransportError("official DSH ACP connection was lost"))
                raise AcpTransportError("official DSH ACP connection was lost") from None

    def _read_loop(self) -> None:
        process = self.process
        if process is None or process.stdout is None:
            self._fail(AcpTransportError("official DSH ACP stdio transport is unavailable"))
            return
        try:
            while True:
                raw = process.stdout.readline(_MAX_FRAME_BYTES + 1)
                if not raw:
                    break
                if len(raw) > _MAX_FRAME_BYTES or not raw.endswith(b"\n"):
                    raise AcpTransportError("official DSH ACP response exceeded the protocol bound")
                try:
                    message = json.loads(raw.decode("utf-8"))
                except (UnicodeError, json.JSONDecodeError, RecursionError):
                    raise AcpTransportError("official DSH ACP returned malformed JSON-RPC") from None
                self._dispatch(message)
        except AcpTransportError as error:
            self._fail(error)
            return
        except BaseException:
            self._fail(AcpTransportError("official DSH ACP connection was lost"))
            return
        self._fail(AcpTransportError("official DSH ACP connection was lost"))

    def _dispatch(self, message: object) -> None:
        if not isinstance(message, dict) or message.get("jsonrpc") != "2.0":
            raise AcpTransportError("official DSH ACP returned malformed JSON-RPC")
        if "method" in message:
            method = message.get("method")
            params = message.get("params", {})
            if not isinstance(method, str) or not isinstance(params, dict):
                raise AcpTransportError("official DSH ACP returned malformed JSON-RPC")
            if "id" in message:
                self._handle_server_request(message["id"], method, params)
            else:
                self._handle_notification(method, params)
            return
        request_id = message.get("id")
        if isinstance(request_id, bool) or not isinstance(request_id, int):
            raise AcpTransportError("official DSH ACP returned an unmatched response")
        if ("result" in message) == ("error" in message):
            raise AcpTransportError("official DSH ACP returned malformed JSON-RPC")
        with self._pending_lock:
            pending = self._pending.pop(request_id, None)
        if pending is None:
            raise AcpTransportError("official DSH ACP returned an unmatched response")
        pending.response = message
        pending.event.set()

    def _handle_notification(self, method: str, params: dict[str, Any]) -> None:
        if method != "session/update":
            return
        session_id = params.get("sessionId")
        update = params.get("update")
        if not isinstance(session_id, str) or not session_id or not isinstance(update, dict):
            raise AcpTransportError("official DSH ACP returned a malformed session update")
        sequence = self.next_sequence(session_id)
        event = AcpNotification(method=method, params=params, event_sequence=sequence)
        with self._notification_lock:
            events = self._notifications.setdefault(session_id, queue.Queue())
        events.put(event)

    def _handle_server_request(self, request_id: object, method: str, params: dict[str, Any]) -> None:
        if isinstance(request_id, bool) or not isinstance(request_id, (int, str)):
            raise AcpTransportError("official DSH ACP returned a malformed request")
        if method == "session/request_permission":
            response = self._reject_permission(params)
        else:
            response = {"jsonrpc": "2.0", "id": request_id,
                        "error": {"code": -32601, "message": "Method not found"}}
            self._write(response)
            return
        self._write({"jsonrpc": "2.0", "id": request_id, "result": response})

    @staticmethod
    def _reject_permission(params: dict[str, Any]) -> dict[str, Any]:
        options = params.get("options")
        if not isinstance(options, list):
            raise AcpTransportError("official DSH ACP permission request was malformed")
        for option in options:
            if (isinstance(option, dict) and option.get("kind") == "reject_once"
                    and isinstance(option.get("optionId"), str) and option["optionId"]):
                return {"outcome": {"outcome": "selected", "optionId": option["optionId"]}}
        raise AcpTransportError("official DSH ACP permission request offered no reject option")

    def _discard_pending(self, pending: _Pending) -> None:
        with self._pending_lock:
            stale = [key for key, value in self._pending.items() if value is pending]
            for key in stale:
                self._pending.pop(key, None)

    def _raise_if_unavailable(self, *, allow_closed_queue: bool = False) -> None:
        if self._fatal is not None:
            raise self._fatal
        if self._closed and not allow_closed_queue:
            raise AcpTransportError("official DSH ACP process is closed")
        process = self.process
        if process is not None and process.poll() is not None and self._fatal is None:
            raise AcpTransportError("official DSH ACP process exited")

    def _fail(self, error: BaseException) -> None:
        with self._pending_lock:
            if self._fatal is None:
                self._fatal = error
            pending = tuple(self._pending.values())
            self._pending.clear()
        for item in pending:
            item.error = error
            item.event.set()
        with self._notification_lock:
            queues = tuple(self._notifications.values())
        for events in queues:
            events.put(error)

    def close(self) -> None:
        process = self.process
        if process is None:
            return
        if not self._closed:
            self._closed = True
            try:
                if process.stdin is not None:
                    process.stdin.close()
            except OSError:
                pass
        if process.poll() is None:
            try:
                process.wait(timeout=3.0)
            except (OSError, subprocess.TimeoutExpired):
                self._terminate(process)
        if process.poll() is None:
            raise AcpTransportError("official DSH ACP process exit could not be confirmed")
        reader = self._reader
        if reader is not None and reader is not threading.current_thread():
            reader.join(timeout=1.0)

    @staticmethod
    def _terminate(process: subprocess.Popen[bytes]) -> None:
        try:
            if os.name == "posix":
                os.killpg(process.pid, signal.SIGTERM)
            else:
                process.terminate()
            process.wait(timeout=1.0)
        except (OSError, ProcessLookupError, subprocess.TimeoutExpired):
            try:
                if os.name == "posix":
                    os.killpg(process.pid, signal.SIGKILL)
                else:
                    process.kill()
            except (OSError, ProcessLookupError):
                pass
            try:
                process.wait(timeout=1.0)
            except (OSError, subprocess.TimeoutExpired):
                pass
        if process.poll() is None:
            raise AcpTransportError("official DSH ACP process exit could not be confirmed")


@dataclass(slots=True)
class AcpHarness:
    """Configuration and live ACP transport for one BYQ runtime root."""

    provider: str
    model: str
    composition: Path
    session_root: Path
    runtime_command: tuple[str, ...]
    environment: dict[str, str] = field(repr=False)
    max_tokens: int | None = None
    private_provider_patch: Path | None = None
    provider_proxy_base_url: str | None = None
    provider_local_token: str | None = field(default=None, repr=False)
    process: _AcpProcess | None = field(default=None, repr=False)
    native_session_ids: set[str] = field(default_factory=set, repr=False)
    lock: threading.RLock = field(default_factory=threading.RLock, repr=False)


@dataclass(frozen=True, slots=True)
class AcpPreparedPrompt:
    harness: AcpHarness = field(repr=False)
    native_session_id: str


@dataclass(slots=True)
class _MessageAssembly:
    message_id: str
    text: list[str] = field(default_factory=list)
    size: int = 0
    sequence: int = 0


class DshAcpCompatibility:
    """Compatibility boundary for official ``dsh-v0.2.0-rc.2`` ACP stdio."""

    family = "dsh-v0.2.0-rc.2-acp"

    def runtime_command(self, runtime_root: Path, node: str) -> tuple[str, ...]:
        """Resolve only a fixed installation-owned launcher, without shell parsing."""
        root = runtime_root.expanduser().resolve()
        for candidate in (root / "bin" / "dsh", root / "dsh"):
            if candidate.is_file() and os.access(candidate, os.X_OK):
                return (str(candidate),)
        js_entry = root / "apps" / "cli" / "lib" / "bin.js"
        if js_entry.is_file():
            return (node, str(js_entry))
        executable = shutil.which("dsh")
        if executable:
            return (executable,)
        raise FileNotFoundError("official DSH ACP launcher is unavailable")

    def build_harness(
        self, *, provider: str, model: str, composition: Path, session_root: Path,
        runtime_command: tuple[str, ...], environment: dict[str, str],
        max_tokens: int | None = None,
        private_provider_patch: Path | None = None,
        provider_proxy_base_url: str | None = None,
        provider_local_token: str | None = None,
    ) -> AcpHarness:
        patch = composition.expanduser().resolve()
        home = session_root.expanduser().resolve()
        if not patch.is_file():
            raise FileNotFoundError("candidate DSH ACP composition is unavailable")
        if not runtime_command or any(not isinstance(part, str) or not part for part in runtime_command):
            raise FileNotFoundError("candidate DSH ACP launcher is unavailable")
        if max_tokens is not None and (type(max_tokens) is not int or max_tokens <= 0):
            raise ValueError("candidate DSH ACP output limit is invalid")
        if not isinstance(environment, dict) or any(
            not isinstance(key, str) or not isinstance(value, str)
            for key, value in environment.items()
        ):
            raise ValueError("candidate DSH ACP environment is invalid")
        self._validate_runtime_identity(environment)
        self._validate_judgment_process_environment(
            environment, provider, provider_local_token)
        self._mcp_servers(environment)
        if (environment.get(_ACP_IDENTITY_MODE_ENV) == _ACP_JUDGMENT_ROOT_MODE
                and private_provider_patch is None):
            raise AcpTransportError("ACP judgment root requires private provider patch")
        if (private_provider_patch is None) != (provider_proxy_base_url is None):
            raise AcpTransportError("ACP judgment private provider patch is incomplete")
        if private_provider_patch is not None:
            if environment.get(_ACP_IDENTITY_MODE_ENV) != _ACP_JUDGMENT_ROOT_MODE:
                raise AcpTransportError("private provider patch requires judgment root")
            self._verify_private_provider_patch(private_provider_patch, provider,
                                                model, provider_proxy_base_url)
        home.mkdir(parents=True, exist_ok=True)
        return AcpHarness(
            provider=provider,
            model=model,
            composition=patch,
            session_root=home,
            runtime_command=tuple(runtime_command),
            environment=dict(environment),
            max_tokens=max_tokens,
            private_provider_patch=(private_provider_patch.expanduser().resolve()
                                    if private_provider_patch is not None else None),
            provider_proxy_base_url=provider_proxy_base_url,
            provider_local_token=provider_local_token,
        )

    def start(self, harness: AcpHarness) -> None:
        with harness.lock:
            if harness.process is not None:
                return
            self._validate_runtime_identity(harness.environment)
            self._validate_judgment_process_environment(
                harness.environment, harness.provider, harness.provider_local_token)
            if (harness.environment.get(_ACP_IDENTITY_MODE_ENV) == _ACP_JUDGMENT_ROOT_MODE
                    and harness.private_provider_patch is None):
                raise AcpTransportError("ACP judgment root requires private provider patch")
            if (harness.private_provider_patch is not None
                    and harness.environment.get(_ACP_IDENTITY_MODE_ENV) != _ACP_JUDGMENT_ROOT_MODE):
                raise AcpTransportError("private provider patch requires judgment root")
            command = [*harness.runtime_command, "--profile", "acp", "--patch", str(harness.composition)]
            if harness.private_provider_patch is not None:
                self._verify_private_provider_patch(
                    harness.private_provider_patch, harness.provider,
                    harness.model, harness.provider_proxy_base_url)
                command.extend(["--patch", str(harness.private_provider_patch)])
            environment = {
                key: os.environ[key]
                for key in _INHERITED_RUNTIME_ENV
                if key in os.environ
            }
            environment.update(harness.environment)
            # Defense in depth for explicit caller environments too. The ACP
            # process must not receive resolver, authority, Backend, or other
            # internal service credentials.
            for key in _INTERNAL_SERVICE_SECRETS:
                environment.pop(key, None)
            # Judgment identity is never ambient. Forward its selector and its
            # sole signing secret only for an explicitly validated fresh root.
            for key in _ACP_JUDGMENT_PROCESS_ENV:
                environment.pop(key, None)
            # Provider keys are credentials, not harmless ambient settings.
            # The Adapter passes exactly the selected route's credential in
            # harness.environment; never inherit the other provider's key (or
            # search-specific credentials) from the Adapter process.
            for key in ("DEEPSEEK_API_KEY", "OPENCODE_API_KEY", "DEEPSEEK_SEARCH_API_KEY"):
                environment.pop(key, None)
            selected_key = {
                "deepseek-official": "DEEPSEEK_API_KEY",
            }.get(harness.provider)
            if harness.provider.startswith("opencode-"):
                selected_key = "OPENCODE_API_KEY"
            if selected_key is not None and selected_key in harness.environment:
                environment[selected_key] = harness.environment[selected_key]
            if harness.environment.get(_ACP_IDENTITY_MODE_ENV) == _ACP_JUDGMENT_ROOT_MODE:
                for key in _ACP_JUDGMENT_PROCESS_ENV:
                    if key in harness.environment:
                        environment[key] = harness.environment[key]
            # The ACP composition authenticates through discovery-only and
            # signed per-Agent credentials. Recovery/continuation selectors
            # are added only when they are explicit in this harness.
            for key in ("BYQ_NATIVE_ROOT_SESSION_ID", "BYQ_CONTINUATION_RESERVATION_ID"):
                if key not in harness.environment:
                    environment.pop(key, None)
            environment.update({
                "DSH_HOME": str(harness.session_root),
                # The Product identity plugin proves the ACP home remains
                # inside this session's private runtime storage root.
                "DSH_SESSION_ROOT": str(harness.session_root.parent),
                "DSH_TELEMETRY_DISABLED": "1",
                "DSH_PERMISSION_MODE": "read-only",
                "DSH_MAX_TOKENS_AS_SUCCESS": "false",
            })
            transport = _AcpProcess(tuple(command), harness.session_root, environment)
            # Publish the handle before start so any startup failure retains a
            # closeable reference for the Runtime Adapter's fail-closed path.
            harness.process = transport
            transport.start()

    def create_session(self, harness: AcpHarness, *, cwd: Path | str | None = None) -> str:
        transport = self._require_process(harness)
        working_directory = self._canonical_cwd(cwd or harness.session_root)
        if transport.environment.get("BYQ_NATIVE_ROOT_SESSION_ID"):
            raise AcpTransportError("fresh ACP root unexpectedly has a persisted native identity")
        result = transport.request("session/new", {
            "cwd": working_directory,
            # Product MCP is composed in DSH scopes. ACP's per-session mount
            # would duplicate it and cannot carry child Agent identity.
            "mcpServers": [],
        }, timeout=_REQUEST_TIMEOUT_SECONDS)
        session_id = _session_id(result)
        self._verify_root_binding(harness, session_id, working_directory)
        self._select_route(transport, session_id, result, harness.provider, harness.model)
        harness.native_session_ids.add(session_id)
        with transport._notification_lock:
            transport._notifications.setdefault(session_id, queue.Queue())
            transport._sequence.setdefault(session_id, 0)
        return session_id

    def resume_session(
        self, harness: AcpHarness, native_session_id: str, *, cwd: Path | str | None = None,
    ) -> str:
        if not isinstance(native_session_id, str) or _NATIVE_SESSION_ID_RE.fullmatch(native_session_id) is None:
            raise ValueError("native ACP session identity is required")
        transport = self._require_process(harness)
        if transport.environment.get("BYQ_NATIVE_ROOT_SESSION_ID") != native_session_id:
            raise AcpTransportError("persisted ACP root identity is not configured for resume")
        working_directory = self._canonical_cwd(cwd or harness.session_root)
        result = transport.request("session/resume", {
            "sessionId": native_session_id,
            "cwd": working_directory,
            "mcpServers": [],
        }, timeout=_REQUEST_TIMEOUT_SECONDS)
        returned_id = _session_id(result, expected=native_session_id)
        self._verify_root_binding(harness, returned_id, working_directory,
                                  expected_native_session_id=native_session_id)
        self._select_route(transport, returned_id, result, harness.provider, harness.model)
        harness.native_session_ids.add(returned_id)
        with transport._notification_lock:
            transport._notifications.setdefault(returned_id, queue.Queue())
            transport._sequence.setdefault(returned_id, 0)
        return returned_id

    def prepare_prompt(self, harness: AcpHarness, session_id: str) -> AcpPreparedPrompt:
        if not isinstance(session_id, str) or session_id not in harness.native_session_ids:
            raise AcpTransportError("native ACP session is unavailable")
        self._require_process(harness)
        return AcpPreparedPrompt(harness=harness, native_session_id=session_id)

    def run_prepared_prompt(
        self, session: AcpPreparedPrompt, content: str,
        on_notification: Callable[[object], None],
    ) -> str:
        if not isinstance(content, str) or not content:
            raise ValueError("ACP prompt must contain text")
        transport = self._require_process(session.harness)
        session_id = session.native_session_id
        self._emit_synthetic(on_notification, transport, "turn/start", session_id, {})
        pending = transport.request_async("session/prompt", {
            "sessionId": session_id,
            "prompt": [{"type": "text", "text": content}],
        })
        assembly: _MessageAssembly | None = None
        callback_failed = False
        cancel_sent = False

        def deliver(notification: object) -> bool:
            nonlocal callback_failed, cancel_sent
            if self._deliver(on_notification, notification):
                return True
            callback_failed = True
            if not cancel_sent:
                self.cancel_session(session.harness, session_id)
                cancel_sent = True
            return False

        def flush_message(message: _MessageAssembly) -> None:
            if not message.text:
                return
            deliver(AcpNotification(
                method="byq/assistant_message",
                params={"sessionId": session_id, "messageId": message.message_id,
                        "text": "".join(message.text)},
                event_sequence=message.sequence,
            ))

        while True:
            try:
                event = transport.next_notification(session_id, 0.05)
            except AcpTransportError:
                raise
            if event is not None:
                update = event.params.get("update")
                update_type = update.get("sessionUpdate") if isinstance(update, dict) else None
                message_id = update.get("messageId") if isinstance(update, dict) else None
                if update_type == "agent_message_chunk" and isinstance(message_id, str) and message_id:
                    if assembly is not None and message_id != assembly.message_id:
                        flush_message(assembly)
                        assembly = None
                    if assembly is None:
                        assembly = _MessageAssembly(message_id)
                    assembly.sequence = event.event_sequence or assembly.sequence
                    block = update.get("content")
                    text = block.get("text") if isinstance(block, dict) and block.get("type") == "text" else None
                    if isinstance(text, str) and text:
                        encoded_size = len(text.encode("utf-8"))
                        if assembly.size + encoded_size > _MAX_TEXT_BYTES:
                            self.cancel_session(session.harness, session_id)
                            raise AcpTransportError("official DSH ACP assistant output exceeded the Adapter bound")
                        assembly.text.append(text)
                        assembly.size += encoded_size
                    continue
                if assembly is not None:
                    flush_message(assembly)
                    assembly = None
                if update_type == "agent_thought_chunk":
                    # Private reasoning is represented only as runtime activity.
                    thought = AcpNotification(event.method, event.params, event.event_sequence)
                    deliver(thought)
                    continue
                deliver(event)
            elif pending.event.is_set():
                break
        try:
            result = transport.await_response(pending)
        except BaseException:
            if assembly is not None:
                flush_message(assembly)
            try:
                self._emit_synthetic(on_notification, transport, "turn/end", session_id,
                                     {"stopReason": "unknown"})
            except AcpTransportError:
                pass
            raise
        if assembly is not None:
            flush_message(assembly)
        stop_reason = result.get("stopReason") if isinstance(result, dict) else None
        if stop_reason not in _FINISH_REASONS:
            stop_reason = "unknown"
        self._emit_synthetic(on_notification, transport, "turn/end", session_id, {"stopReason": stop_reason})
        if callback_failed:
            raise AcpTransportError("ACP update consumer failed")
        return _FINISH_REASONS.get(stop_reason, "failed")

    def prompt(
        self, harness: AcpHarness, session_id: str, content: str,
        on_notification: Callable[[object], None],
    ) -> str:
        return self.run_prepared_prompt(self.prepare_prompt(harness, session_id), content, on_notification)

    def cancel_session(self, harness: AcpHarness, native_session_id: str) -> None:
        self._require_process(harness).notify("session/cancel", {"sessionId": native_session_id})

    def close_session(self, harness: AcpHarness, native_session_id: str) -> None:
        transport = self._require_process(harness)
        transport.request("session/close", {"sessionId": native_session_id}, timeout=_REQUEST_TIMEOUT_SECONDS)
        harness.native_session_ids.discard(native_session_id)

    def close(self, harness: AcpHarness) -> None:
        with harness.lock:
            transport = harness.process
        if transport is not None:
            transport.close()
            process = transport.process
            if process is None or process.poll() is None:
                raise AcpTransportError("official DSH ACP process exit could not be confirmed")
            with harness.lock:
                if harness.process is transport:
                    harness.process = None

    @staticmethod
    def observe(notification: object, *, root_session_id: str) -> RuntimeObservation:
        if not isinstance(notification, AcpNotification):
            return RuntimeObservation(kind="ignored")
        params = notification.params
        session_id = params.get("sessionId")
        if not isinstance(session_id, str) or not session_id:
            return RuntimeObservation(kind="ignored", event_sequence=notification.event_sequence)
        is_root = session_id == root_session_id
        sequence = notification.event_sequence
        if notification.method == "byq/turn/start":
            return RuntimeObservation(
                kind="turn.start", session_id=session_id, root_session=is_root,
                runtime_activity=True, event_sequence=sequence,
            )
        if notification.method == "byq/turn/end":
            reason = params.get("stopReason")
            terminal = _FINISH_REASONS.get(reason, "failed")
            return RuntimeObservation(
                kind="turn.end", session_id=session_id, root_session=is_root,
                runtime_activity=True, event_sequence=sequence, terminal_reason=terminal,
            )
        if notification.method == "byq/assistant_message":
            text = params.get("text")
            message_id = params.get("messageId")
            valid = isinstance(text, str) and bool(text)
            return RuntimeObservation(
                kind="assistant.message" if valid else "ignored",
                session_id=session_id, root_session=is_root, runtime_activity=valid,
                event_sequence=sequence,
                message_id=message_id if isinstance(message_id, str) and message_id else None,
                answer_text=text if valid else None,
            )
        if notification.method != "session/update":
            return RuntimeObservation(kind="ignored", session_id=session_id, root_session=is_root,
                                     event_sequence=sequence)
        update = params.get("update")
        if not isinstance(update, dict):
            return RuntimeObservation(kind="ignored", session_id=session_id, root_session=is_root,
                                     event_sequence=sequence)
        update_type = update.get("sessionUpdate")
        if update_type == "agent_message_chunk":
            content = update.get("content")
            text = content.get("text") if isinstance(content, dict) and content.get("type") == "text" else None
            message_id = update.get("messageId")
            valid = isinstance(text, str) and bool(text)
            return RuntimeObservation(
                kind="assistant.message" if valid else "ignored",
                session_id=session_id, root_session=is_root, runtime_activity=valid,
                event_sequence=sequence,
                message_id=message_id if isinstance(message_id, str) and message_id else None,
                answer_text=text if valid else None,
            )
        if update_type == "agent_thought_chunk":
            return RuntimeObservation(kind="private.activity", session_id=session_id,
                                      root_session=is_root, runtime_activity=True,
                                      event_sequence=sequence)
        if update_type == "tool_call":
            call_id, name = update.get("toolCallId"), update.get("title")
            valid = isinstance(call_id, str) and bool(call_id) and isinstance(name, str) and bool(name)
            arguments = update.get("rawInput")
            return RuntimeObservation(
                kind="tool.call" if valid else "ignored", session_id=session_id,
                root_session=is_root, runtime_activity=valid, event_sequence=sequence,
                call_id=call_id if isinstance(call_id, str) else None,
                tool_name=name if isinstance(name, str) else None,
                registration_key=_registration_key(name, arguments) if valid else None,
                domain_arguments=_domain_arguments(name, arguments) if valid else None,
            )
        if update_type == "tool_call_update":
            status = update.get("status")
            call_id = update.get("toolCallId")
            if status not in {"completed", "failed"} or not isinstance(call_id, str) or not call_id:
                return RuntimeObservation(kind="ignored", session_id=session_id,
                                          root_session=is_root, event_sequence=sequence)
            failed = status == "failed"
            result = _tool_result_value(update.get("content"), failed=failed)
            tool_result = RuntimeToolResult(call_id, failed, result)
            return RuntimeObservation(
                kind="tool.result", session_id=session_id, root_session=is_root,
                runtime_activity=True, event_sequence=sequence, call_id=call_id,
                tool_failed=failed, tool_result=result, completed_call_ids=(call_id,),
                tool_results=(tool_result,),
            )
        if update_type == "usage_update":
            # ACP exposes context occupancy, not per-call token usage. Do not
            # misclassify it as billable or budget-consumable model usage.
            return RuntimeObservation(kind="private.activity", session_id=session_id,
                                      root_session=is_root, runtime_activity=True,
                                      event_sequence=sequence)
        return RuntimeObservation(kind="ignored", session_id=session_id, root_session=is_root,
                                  event_sequence=sequence)

    @staticmethod
    def _emit_synthetic(
        callback: Callable[[object], None], transport: _AcpProcess, method: str,
        session_id: str, extra: dict[str, Any],
    ) -> None:
        params = {"sessionId": session_id, **extra}
        event = AcpNotification(method=f"byq/{method}", params=params,
                                event_sequence=transport.next_sequence(session_id))
        if not DshAcpCompatibility._deliver(callback, event):
            raise AcpTransportError("ACP update consumer failed")

    @staticmethod
    def _deliver(callback: Callable[[object], None], notification: object) -> bool:
        try:
            callback(notification)
            return True
        except Exception:
            return False

    @staticmethod
    def _require_process(harness: AcpHarness) -> _AcpProcess:
        process = harness.process
        if process is None or not process.initialized:
            raise AcpTransportError("official DSH ACP process is not initialized")
        return process

    @staticmethod
    def _canonical_cwd(cwd: Path | str) -> str:
        path = Path(cwd).expanduser().resolve(strict=True)
        if not path.is_dir():
            raise ValueError("ACP session cwd must be a directory")
        return str(path)

    @staticmethod
    def _mcp_servers(environment: dict[str, str]) -> list[dict[str, Any]]:
        """ACP mounts no Product MCP client; DSH composition owns scoped clients."""
        reservation_id = environment.get("BYQ_CONTINUATION_RESERVATION_ID")
        if reservation_id is not None:
            if (re.fullmatch(r"[0-9a-f]{32}", environment.get("BYQ_ROOT_RUN_ID", "")) is None
                    or re.fullmatch(r"continuation_[0-9a-f]{32}", reservation_id) is None):
                raise AcpTransportError("continuation MCP authority identity is invalid")
        return []

    @staticmethod
    def _verify_private_provider_patch(
        patch: Path, provider: str, model: str, proxy_base_url: str | None,
    ) -> None:
        try:
            path = Path(patch)
            directory = os.lstat(path.parent)
            info = os.lstat(path)
            if (not stat.S_ISDIR(directory.st_mode)
                    or stat.S_IMODE(directory.st_mode) & 0o077
                    or directory.st_uid != os.geteuid()
                    or not stat.S_ISREG(info.st_mode)
                    or stat.S_IMODE(info.st_mode) != 0o600
                    or info.st_uid != os.geteuid() or info.st_nlink != 1
                    or info.st_size > 16 * 1024):
                raise ValueError("private provider patch file is invalid")
            fd = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
            with os.fdopen(fd, "rb") as source:
                opened = os.fstat(source.fileno())
                if (opened.st_dev, opened.st_ino) != (info.st_dev, info.st_ino):
                    raise ValueError("private provider patch changed")
                raw = source.read(16 * 1024 + 1)
            expected = private_provider_overlay(
                route_name=provider, model=model, proxy_base_url=proxy_base_url)
            expected_raw = json.dumps(expected, sort_keys=True,
                                      separators=(",", ":")).encode()
            if raw != expected_raw:
                raise ValueError("private provider patch differs from selection")
        except (OSError, ValueError, TypeError, UnicodeError, json.JSONDecodeError):
            raise AcpTransportError("ACP judgment private provider patch is invalid") from None

    @staticmethod
    def _validate_judgment_process_environment(
        environment: dict[str, str], provider: str,
        provider_local_token: str | None,
    ) -> None:
        if environment.get(_ACP_IDENTITY_MODE_ENV) != _ACP_JUDGMENT_ROOT_MODE:
            if provider_local_token is not None:
                raise AcpTransportError("local provider token requires judgment root")
            return
        provider_key = ("DEEPSEEK_API_KEY" if provider == "deepseek-official"
                        else "OPENCODE_API_KEY" if provider in _ACP_JUDGMENT_OPENCODE_ROUTES
                        else None)
        if provider_key is None or set(environment) - (_ACP_JUDGMENT_ALLOWED_ENV | {provider_key}):
            raise AcpTransportError("ACP judgment process environment contains unapproved entries")
        if (not valid_local_provider_token(provider_local_token)
                or not valid_local_provider_token(environment.get(provider_key))
                or not hmac.compare_digest(environment[provider_key], provider_local_token)):
            raise AcpTransportError("ACP judgment process requires its exact local provider token")

    @staticmethod
    def _validate_runtime_identity(environment: dict[str, str]) -> None:
        identity_mode = environment.get(_ACP_IDENTITY_MODE_ENV)
        judgment_root = identity_mode == _ACP_JUDGMENT_ROOT_MODE
        if identity_mode is not None and not judgment_root:
            raise AcpTransportError("ACP Product MCP identity mode is invalid")
        if not judgment_root and any(key in environment for key in _ACP_JUDGMENT_PROCESS_ENV):
            raise AcpTransportError("ACP judgment identity is not allowed on the Product root")
        required = (
            "BYQ_MCP_URL", "BYQ_RUNTIME_BOOT_ID", "BYQ_OWNER_PRINCIPAL",
            "BYQ_WORKSPACE_ID", "BYQ_ACTOR_PRINCIPAL", "BYQ_TRACE_ID",
            "BYQ_SESSION_ID", "BYQ_DSH_RUN_ID", "BYQ_ROOT_RUN_ID",
        )
        if judgment_root:
            required += (
                "BYQ_MCP_ACP_JUDGMENT_TASK_ID",
                "BYQ_MCP_ACP_JUDGMENT_CALL_IDENTITY",
                "BYQ_MCP_ACP_JUDGMENT_SIGNING_KEY",
                "BYQ_MCP_PRODUCT_URL",
            )
            if any(key in environment for key in _ACP_JUDGMENT_FORBIDDEN_ENV):
                raise AcpTransportError("ACP judgment identity contains Product credentials")
        else:
            required += ("BYQ_MCP_ACP_DISCOVERY_TOKEN", "BYQ_MCP_ACP_SIGNING_KEY")
        if any(not environment.get(key) for key in required):
            raise AcpTransportError("ACP Product MCP identity configuration is incomplete")
        endpoint = environment["BYQ_MCP_URL"]
        parsed = urlsplit(endpoint)
        if (parsed.scheme not in {"http", "https"} or not parsed.hostname
                or parsed.username is not None or parsed.password is not None
                or parsed.query or parsed.fragment):
            raise AcpTransportError("ACP Product MCP endpoint is invalid")
        if judgment_root:
            signing_key = environment["BYQ_MCP_ACP_JUDGMENT_SIGNING_KEY"]
            if len(signing_key.encode("utf-8")) < 32:
                raise AcpTransportError("ACP judgment signing key is invalid")
            for product_endpoint_name in ("BYQ_MCP_PRODUCT_URL", "BYQ_MCP_READ_ONLY_URL"):
                if product_endpoint_name not in environment:
                    continue
                product_endpoint_value = environment[product_endpoint_name]
                product_endpoint = urlsplit(product_endpoint_value)
                if (product_endpoint.scheme not in {"http", "https"}
                        or not product_endpoint.hostname
                        or product_endpoint.username is not None
                        or product_endpoint.password is not None
                        or product_endpoint.query or product_endpoint.fragment
                        or endpoint == product_endpoint_value):
                    raise AcpTransportError("ACP judgment MCP endpoint is not isolated")
            if re.fullmatch(r"task_[0-9a-f]{32}",
                            environment["BYQ_MCP_ACP_JUDGMENT_TASK_ID"]) is None:
                raise AcpTransportError("ACP judgment task identity is invalid")
            if re.fullmatch(r"byq-judgment-[0-9a-f]{32}",
                            environment["BYQ_MCP_ACP_JUDGMENT_CALL_IDENTITY"]) is None:
                raise AcpTransportError("ACP judgment call identity is invalid")
        else:
            if len(environment["BYQ_MCP_ACP_SIGNING_KEY"].encode("utf-8")) < 32:
                raise AcpTransportError("ACP Product MCP signing key is invalid")
            distinct = [environment["BYQ_MCP_ACP_DISCOVERY_TOKEN"],
                        environment["BYQ_MCP_ACP_SIGNING_KEY"]]
            if environment.get("BYQ_MCP_TOKEN"):
                distinct.append(environment["BYQ_MCP_TOKEN"])
            if len(set(distinct)) != len(distinct):
                raise AcpTransportError("ACP Product MCP credentials must be distinct")
        if re.fullmatch(r"[0-9a-f]{32}", environment["BYQ_RUNTIME_BOOT_ID"]) is None:
            raise AcpTransportError("ACP Product runtime boot identity is invalid")
        if re.fullmatch(r"[0-9a-f]{32}", environment["BYQ_ROOT_RUN_ID"]) is None:
            raise AcpTransportError("ACP Product root identity is invalid")
        principal = r"[A-Za-z0-9][A-Za-z0-9_.:@/-]{0,127}"
        trace = r"[A-Za-z0-9][A-Za-z0-9_-]{0,63}"
        for key in ("BYQ_OWNER_PRINCIPAL", "BYQ_ACTOR_PRINCIPAL"):
            if re.fullmatch(principal, environment[key]) is None:
                raise AcpTransportError("ACP Product principal identity is invalid")
        for key in ("BYQ_WORKSPACE_ID", "BYQ_TRACE_ID", "BYQ_SESSION_ID", "BYQ_DSH_RUN_ID"):
            if re.fullmatch(trace, environment[key]) is None:
                raise AcpTransportError("ACP Product session identity is invalid")
        expected_actor = f"byq-product-agent-{environment['BYQ_SESSION_ID']}"
        if environment["BYQ_ACTOR_PRINCIPAL"] != expected_actor:
            raise AcpTransportError("ACP Product actor identity is invalid")
        expected_native_id = environment.get("BYQ_NATIVE_ROOT_SESSION_ID")
        if expected_native_id is not None and _NATIVE_SESSION_ID_RE.fullmatch(expected_native_id) is None:
            raise AcpTransportError("persisted ACP root identity is invalid")

    @staticmethod
    def _verify_root_binding(
        harness: AcpHarness,
        native_session_id: str,
        cwd: str,
        *,
        expected_native_session_id: str | None = None,
    ) -> None:
        marker = harness.session_root / _ROOT_BINDING_MARKER
        try:
            marker_info = os.lstat(marker)
            if not stat.S_ISREG(marker_info.st_mode) or stat.S_IMODE(marker_info.st_mode) != 0o600:
                raise ValueError("binding marker is not a private regular file")
            if marker_info.st_size > 4096:
                raise ValueError("binding marker exceeds its bound")
            flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
            descriptor = os.open(marker, flags)
            with os.fdopen(descriptor, "rb") as source:
                opened_info = os.fstat(source.fileno())
                if (opened_info.st_dev, opened_info.st_ino) != (marker_info.st_dev, marker_info.st_ino):
                    raise ValueError("binding marker changed while opening")
                raw = source.read(4097)
            if len(raw) > 4096:
                raise ValueError("binding marker exceeds its bound")
            value = json.loads(raw.decode("utf-8"), object_pairs_hook=_strict_object)
            if (not isinstance(value, dict)
                    or set(value) != {"schema_version", "native_root_session_id", "cwd"}
                    or value["schema_version"] != "byq-acp-root-binding.v1"
                    or value["native_root_session_id"] != native_session_id
                    or value["cwd"] != cwd
                    or (expected_native_session_id is not None
                        and value["native_root_session_id"] != expected_native_session_id)):
                raise ValueError("binding marker does not match the ACP root")
        except (OSError, ValueError, TypeError, UnicodeError, json.JSONDecodeError, RecursionError):
            raise AcpTransportError("official DSH ACP root binding could not be verified") from None

    @staticmethod
    def _select_route(
        transport: _AcpProcess, session_id: str, new_or_resume: Any,
        provider: str, model: str,
    ) -> None:
        options = new_or_resume.get("configOptions") if isinstance(new_or_resume, dict) else None
        model_option = next((item for item in options if isinstance(item, dict)
                             and item.get("id") == _MODEL_CONFIG_ID), None) if isinstance(options, list) else None
        groups = model_option.get("options") if isinstance(model_option, dict) else None
        expected = json.dumps([provider, model], ensure_ascii=False, separators=(",", ":"))
        match = None
        if isinstance(groups, list):
            for group in groups:
                if not isinstance(group, dict) or group.get("group") != provider:
                    continue
                entries = group.get("options")
                if isinstance(entries, list):
                    match = next((entry for entry in entries if isinstance(entry, dict)
                                  and entry.get("value") == expected), None)
                break
        if match is None:
            raise AcpTransportError("configured model route is not advertised by official DSH ACP")
        transport.request("session/set_config_option", {
            "sessionId": session_id,
            "configId": _MODEL_CONFIG_ID,
            "value": expected,
        }, timeout=_REQUEST_TIMEOUT_SECONDS)


def _session_id(value: object, *, expected: str | None = None) -> str:
    session_id = value.get("sessionId") if isinstance(value, dict) else None
    if not isinstance(session_id, str) or _NATIVE_SESSION_ID_RE.fullmatch(session_id) is None:
        raise AcpTransportError("official DSH ACP did not return a native session identity")
    if expected is not None and session_id != expected:
        raise AcpTransportError("official DSH ACP resumed a different native session")
    return session_id


def _strict_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def _domain_arguments(name: object, raw_input: object) -> dict[str, Any] | None:
    if not isinstance(name, str) or not name.startswith("mcp__byq__"):
        return None
    action = name.removeprefix("mcp__byq__")
    if action not in ACTIONS:
        return None
    encoded = _canonical_json_object(raw_input, max_bytes=65_536)
    if encoded is None:
        return None
    try:
        return parse_observed_arguments(encoded, action=action)
    except ValueError:
        return None


def _registration_key(name: object, raw_input: object) -> str | None:
    if name != "mcp__byq__byq_agent_run_start":
        return None
    encoded = _canonical_json_object(raw_input, max_bytes=4096)
    if encoded is None:
        return None
    try:
        arguments = json.loads(encoded)
    except (ValueError, TypeError, RecursionError):
        return None
    key = arguments.get("idempotency_key") if isinstance(arguments, dict) else None
    if isinstance(arguments, dict) and arguments.get("receipt_only") is True:
        return None
    if not isinstance(key, str) or not 1 <= len(key.strip()) <= 128:
        return None
    return key.strip()


def _canonical_json_object(value: object, *, max_bytes: int) -> str | None:
    if not isinstance(value, dict) or any(not isinstance(key, str) for key in value):
        return None
    try:
        encoded = json.dumps(value, ensure_ascii=False, sort_keys=True,
                             separators=(",", ":"), allow_nan=False)
        if len(encoded.encode("utf-8")) > max_bytes:
            return None
    except (TypeError, ValueError, UnicodeError, RecursionError):
        return None
    return encoded


def _tool_result_value(content: object, *, failed: bool) -> dict[str, Any] | None:
    if not isinstance(content, list):
        return None
    pieces: list[str] = []
    size = 0
    for item in content:
        if not isinstance(item, dict) or item.get("type") != "content":
            continue
        block = item.get("content")
        text = block.get("text") if isinstance(block, dict) and block.get("type") == "text" else None
        if not isinstance(text, str):
            continue
        size += len(text.encode("utf-8"))
        if size > _MAX_TOOL_RESULT_BYTES:
            return None
        pieces.append(text)
    raw = "".join(pieces)
    candidates = [raw]
    if failed and raw.startswith("Error: "):
        first_line = raw.split("\n", 1)[0]
        if len(first_line.encode("utf-8")) <= 4096:
            candidates.insert(0, first_line[7:])
    for candidate in candidates:
        try:
            value = json.loads(candidate, object_pairs_hook=_unique_object)
        except (ValueError, TypeError, RecursionError):
            continue
        if isinstance(value, dict):
            return value
    return None


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate tool result field")
        result[key] = value
    return result


__all__ = [
    "AcpHarness", "AcpNotification", "AcpPreparedPrompt", "AcpRpcError",
    "AcpTransportError", "DshAcpCompatibility",
]
